name: SQL Lint & Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sqlfluff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff sqlfluff-templater-dbt
      - name: Lint SQL files
        run: |
          sqlfluff lint sql/*.sql || true
